# Generated by Django 5.2.7 on 2025-10-28 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
