# Generated by Django 5.2.7 on 2025-10-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='color',
            field=models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('purple', 'Purple'), ('red', 'Red'), ('yellow', 'Yellow')], default='blue', max_length=20),
        ),
    ]
