# Generated by Django 5.2.6 on 2025-11-04 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_schedule_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='model_file',
            field=models.FileField(blank=True, null=True, upload_to='floors/models/'),
        ),
    ]
