# Generated by Django 5.2.6 on 2025-11-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_useractivity_description_useractivity_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.CharField(choices=[('schedule_add', 'Added Schedule'), ('schedule_delete', 'Deleted Schedule'), ('room_view', 'Viewed Room'), ('floor_view', 'Viewed Floor'), ('user_create', 'Created User'), ('user_delete', 'Deleted User'), ('user_modify', 'Modified User'), ('user_update', 'Updated User'), ('room_create', 'Created Room'), ('room_delete', 'Deleted Room'), ('room_modify', 'Modified Room'), ('floor_create', 'Created Floor'), ('floor_delete', 'Deleted Floor'), ('floor_modify', 'Modified Floor'), ('login', 'User Login'), ('logout', 'User Logout')], max_length=20),
        ),
    ]
