# Generated by Django 5.2.6 on 2025-11-14 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_useractivity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='csv_file',
            field=models.FileField(blank=True, null=True, upload_to='floors/csv/'),
        ),
    ]
