# Generated by Django 5.2.7 on 2025-11-14 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_floor_csv_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/images/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_images', to='main.room')),
            ],
            options={
                'ordering': ['upload_date'],
            },
        ),
    ]
