# Generated by Django 5.2.7 on 2025-11-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('regular', 'Regular'), ('admin', 'Admin')], default='regular', max_length=10),
        ),
    ]
