# Generated by Django 5.2.7 on 2025-11-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='floorplan_svg',
            field=models.FileField(blank=True, null=True, upload_to='floors/floorplans/'),
        ),
    ]
