# Generated by Django 5.2.7 on 2025-11-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_consolidate_room_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='room_text',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
