# Generated by Django 5.2.7 on 2025-11-29 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_college_profile_college'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
